services:
- type: web
  name: wifi-voucher-api
  env: docker
  plan: free
  autoDeploy: true
  region: frankfurt
  dockerfilePath: ./Dockerfile
  envVars:
  - key: JWT_SECRET
    generateValue: true
  - key: DB_FILE
    value: /data/app.db
  - key: PORT
    value: 8080
 
